### ISSUE TITLE
Source code not up-to-date?

### ISSUE THREAD

**Issue by CompeyDev** [Tektonikal/CustomBlockHighlight#2]
The main branch seems to only include code for 1.19.4 - and the 1.20.6 release on modrinth has a manifest which is hardcoded to be 1.20.5 only.

**Comment by Tektonikal** [comment]
Sorry for the late reply, been busy with a lot of stuff. The 1.20.5/6 release is probably due to YACL's changes to the toolchain and me being stupid; I'll fix it ASAP. As for the repository being outdated, I'll go through the process of syncing the GH repo with my local one as soon as I get a 1.21 version published. I'll close the issue when I'm done.

**Comment by Tektonikal** [comment]
Finally done, sorry for the wait. I hope the update was worth waiting for
